name: Test Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a test file
        run: echo "This is a test file." > test.txt

      - name: Upload test artifact
        uses: actions/upload-artifact@v4  # or a specific SHA if needed
        with:
          name: test-artifact
          path: test.txt
